### ISSUE TITLE
Buddle.js

### ISSUE THREAD

**Issue by matteocattelan** [mattdesl/svg-mesh-3d#3]
Hi,
your svg-mesh-3d is great but if i download it, not work because miss the buddle.js file.
Is correct?

Is possible to have this file not minimized?

ThKs a lot

**Comment by escapedcat** [comment]
I guess you mean `bundle.js`
After cloning the repo run this in the root folder:

``` bash
npm install
```

After everything is installed [run this](https://github.com/mattdesl/svg-mesh-3d/blob/master/package.json#L46):

```
npm start
```

It will run the script to create the `bundle.js` and start a local server...

``` bash
info budo: Server running at http://10.119.8.103:9966/ (connect)
info budo: LiveReload running on 35729
info browserify: /bundle.js 3002695 5597ms (bundle)
info http: GET /bundle.js 200 2ms (generated)
```

Then you can open `http://10.119.8.103:9966` with your browser.

**Comment by mattdesl** [comment]
^ Yup! Thanks @escapedcat  :+1:
